#!/bin/sh

if [ -e "$HOME/.Xresources" ]
then
   xrdb $HOME/.Xresources
fi

# Map Alt to Meta key
xmodmap -e 'keysym Alt_L = Meta_L' -e 'keysym Alt_R = Meta_R'
# If not working try:
# xmodmap -e "clear Mod1" -e "add Mod1 = Meta_L Meta_R"

startfluxbox &
